version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passe
      MYSQL_DATABASE: keahire_db
      MYSQL_USER: root
      MYSQL_PASSWORD: passe
      MYSQL_PORT: 3366

  mongodb:
    image: bitnami/mongodb:latest
    volumes:
      - mongodb_data:/bitnami/mongodb
    restart: always


  app:
    depends_on:
      - mongodb
      - db
    image: kea_hire:latest
    ports:
      - "3000:3000"
    restart: always



volumes:
  db_data: {}
  mongodb_data: {}
